import type { CalculatorDefinition } from "./types";
import { calculatorCatalog, getCalculatorMeta } from "@/data/calculators/catalog";
import { computeFunctions } from "./compute/all";

function def(slug: string, fields: CalculatorDefinition["fields"], results: CalculatorDefinition["results"]): CalculatorDefinition {
  const meta = getCalculatorMeta(slug)!;
  return { ...meta, fields, results };
}

export const calculatorDefinitions: Record<string, CalculatorDefinition> = {
  "accelerated-payoff-auto": def("accelerated-payoff-auto", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "0", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "0", suffix: "$" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
    { id: "extraPayment", label: "Extra Payment", defaultValue: "0", suffix: "$" },
  ], [
    { id: "standardMonths", label: "Standard Payoff", format: "months" },
    { id: "acceleratedMonths", label: "Accelerated Payoff", format: "months" },
    { id: "monthsSaved", label: "Months Saved", format: "months", highlight: true },
    { id: "standardInterest", label: "Standard Interest", format: "currency" },
    { id: "acceleratedInterest", label: "Accelerated Interest", format: "currency" },
    { id: "interestSaved", label: "Interest Saved", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "car-depreciation": def("car-depreciation", [
    { id: "purchasePrice", label: "Purchase Price", defaultValue: "35000", suffix: "$" },
    { id: "yearsOwned", label: "Years Owned", defaultValue: "3", suffix: "years" },
    { id: "annualDepreciationPercent", label: "Annual Depreciation", defaultValue: "15", suffix: "%", step: "0.1" },
  ], [
    { id: "currentValue", label: "Current Value", format: "currency", highlight: true },
    { id: "totalDepreciation", label: "Total Depreciation", format: "currency" },
    { id: "depreciationPercent", label: "Depreciation", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "ev-savings": def("ev-savings", [
    { id: "annualMiles", label: "Annual Miles", defaultValue: "12000" },
    { id: "gasPrice", label: "Gas Price", defaultValue: "3.5", suffix: "$" },
    { id: "gasMpg", label: "Gas MPG", defaultValue: "25" },
    { id: "evEfficiency", label: "EV Efficiency (kWh/100 mi)", defaultValue: "30" },
    { id: "electricityRate", label: "Electricity Rate", defaultValue: "0.15", suffix: "$" },
    { id: "gasMaintenance", label: "Gas Maintenance (Annual)", defaultValue: "1200", suffix: "$" },
    { id: "evMaintenance", label: "EV Maintenance (Annual)", defaultValue: "600", suffix: "$" },
    { id: "years", label: "Years", defaultValue: "5", suffix: "years" },
  ], [
    { id: "annualGasCost", label: "Annual Gas Cost", format: "currency" },
    { id: "annualEvCost", label: "Annual EV Cost", format: "currency" },
    { id: "annualSavings", label: "Annual Savings", format: "currency", highlight: true },
    { id: "totalSavings", label: "Total Savings", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "car-affordability": def("car-affordability", [
    { id: "monthlyIncome", label: "Monthly Income", defaultValue: "5000", suffix: "$" },
    { id: "monthlyDebts", label: "Monthly Debts", defaultValue: "500", suffix: "$" },
    { id: "maxPaymentPercent", label: "Max Payment (% of Income)", defaultValue: "15", suffix: "%", step: "0.1" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
    { id: "downPayment", label: "Down Payment", defaultValue: "3000", suffix: "$" },
  ], [
    { id: "maxMonthlyPayment", label: "Max Monthly Payment", format: "currency", highlight: true },
    { id: "maxLoanAmount", label: "Max Loan Amount", format: "currency", highlight: true },
    { id: "maxCarPrice", label: "Max Car Price", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "car-payments": def("car-payments", [
    { id: "vehiclePrice", label: "Vehicle Price", defaultValue: "30000", suffix: "$" },
    { id: "downPayment", label: "Down Payment", defaultValue: "3000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
    { id: "monthlyBudget", label: "Monthly Budget", defaultValue: "400", suffix: "$" },
  ], [
    { id: "loanAmount", label: "Loan Amount", format: "currency" },
    { id: "monthlyPayment", label: "Monthly Payment", format: "currency", highlight: true },
    { id: "totalInterest", label: "Total Interest", format: "currency" },
    { id: "totalPaid", label: "Total Paid", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "lease-or-buy-car": def("lease-or-buy-car", [
    { id: "buyPrice", label: "Purchase Price", defaultValue: "35000", suffix: "$" },
    { id: "downPayment", label: "Down Payment", defaultValue: "3000", suffix: "$" },
    { id: "loanRate", label: "Loan Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "loanMonths", label: "Loan Term (Months)", defaultValue: "60", suffix: "months" },
    { id: "leaseDownPayment", label: "Lease Down Payment", defaultValue: "2000", suffix: "$" },
    { id: "leaseMonthly", label: "Lease Monthly Payment", defaultValue: "399", suffix: "$" },
    { id: "leaseMonths", label: "Lease Term (Months)", defaultValue: "36", suffix: "months" },
    { id: "residualValue", label: "Residual Value", defaultValue: "18000", suffix: "$" },
  ], [
    { id: "buyTotalCost", label: "Buy Total Cost", format: "currency" },
    { id: "leaseTotalCost", label: "Lease Total Cost", format: "currency" },
    { id: "buyNetCost", label: "Buy Net Cost", format: "currency", highlight: true },
    { id: "leaseNetCost", label: "Lease Net Cost", format: "currency", highlight: true },
    { id: "costDifference", label: "Cost Difference", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "auto-loan-ltv": def("auto-loan-ltv", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "25000", suffix: "$" },
    { id: "vehicleValue", label: "Vehicle Value", defaultValue: "28000", suffix: "$" },
  ], [
    { id: "ltvRatio", label: "LTV Ratio", format: "percent", highlight: true },
    { id: "equity", label: "Equity", format: "currency" },
    { id: "underwater", label: "Underwater", format: "number", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "loan-vs-dealer-financing": def("loan-vs-dealer-financing", [
    { id: "vehiclePrice", label: "Vehicle Price", defaultValue: "30000", suffix: "$" },
    { id: "bankRate", label: "Bank Rate", defaultValue: "5.5", suffix: "%", step: "0.1" },
    { id: "bankMonths", label: "Bank Term (Months)", defaultValue: "60" },
    { id: "dealerRebate", label: "Dealer Rebate", defaultValue: "2000", suffix: "$" },
    { id: "downPayment", label: "Down Payment", defaultValue: "0", suffix: "$" },
  ], [
    { id: "bankMonthlyPayment", label: "Bank Monthly Payment", format: "currency" },
    { id: "bankTotalInterest", label: "Bank Total Interest", format: "currency" },
    { id: "bankTotalCost", label: "Bank Total Cost", format: "currency" },
    { id: "dealerTotalCost", label: "Dealer Total Cost", format: "currency" },
    { id: "savings", label: "Savings", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "business-valuation": def("business-valuation", [
    { id: "annualEarnings", label: "Annual Earnings", defaultValue: "250000", suffix: "$" },
    { id: "earningsMultiple", label: "Earnings Multiple", defaultValue: "4" },
  ], [
    { id: "businessValue", label: "Business Value", format: "currency", highlight: true },
    { id: "earningsMultiple", label: "Earnings Multiple", format: "number" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "debt-to-equity": def("debt-to-equity", [
    { id: "totalDebt", label: "Total Debt", defaultValue: "500000", suffix: "$" },
    { id: "totalEquity", label: "Total Equity", defaultValue: "750000", suffix: "$" },
  ], [
    { id: "debtToEquityRatio", label: "Debt-to-Equity Ratio", format: "currency", highlight: true },
    { id: "totalDebt", label: "Total Debt", format: "currency" },
    { id: "totalEquity", label: "Total Equity", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "cash-flow-projection": def("cash-flow-projection", [
    { id: "startingCash", label: "Starting Cash", defaultValue: "50000", suffix: "$" },
    { id: "annualRevenue", label: "Annual Revenue", defaultValue: "500000", suffix: "$" },
    { id: "annualExpenses", label: "Annual Expenses", defaultValue: "400000", suffix: "$" },
    { id: "growthRate", label: "Growth Rate", defaultValue: "5", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "5", suffix: "years" },
  ], [
    { id: "year1Cash", label: "Year 1 Cash", format: "currency" },
    { id: "finalCash", label: "Final Cash", format: "currency" },
    { id: "totalNetCashFlow", label: "Total Net Cash Flow", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "freelancer-rate": def("freelancer-rate", [
    { id: "desiredAnnualIncome", label: "Desired Annual Income", defaultValue: "75000", suffix: "$" },
    { id: "annualExpenses", label: "Annual Expenses", defaultValue: "15000", suffix: "$" },
    { id: "billableHours", label: "Billable Hours", defaultValue: "1200" },
    { id: "utilizationPercent", label: "Utilization", defaultValue: "75", suffix: "%", step: "0.1" },
  ], [
    { id: "requiredHourlyRate", label: "Required Hourly Rate", format: "currency", highlight: true },
    { id: "requiredAnnualRevenue", label: "Required Annual Revenue", format: "currency" },
    { id: "effectiveBillableHours", label: "Effective Billable Hours", format: "number" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "net-profit-margin": def("net-profit-margin", [
    { id: "revenue", label: "Revenue", defaultValue: "500000", suffix: "$" },
    { id: "expenses", label: "Expenses", defaultValue: "400000", suffix: "$" },
  ], [
    { id: "netProfit", label: "Net Profit", format: "currency", highlight: true },
    { id: "netProfitMargin", label: "Net Profit Margin", format: "percent", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "buy-now-vs-wait": def("buy-now-vs-wait", [
    { id: "purchasePrice", label: "Purchase Price", defaultValue: "2000", suffix: "$" },
    { id: "savingsRate", label: "Savings Rate", defaultValue: "4", suffix: "%", step: "0.1" },
    { id: "monthsToSave", label: "Months to Save", defaultValue: "12", suffix: "months" },
    { id: "creditRate", label: "Credit Rate", defaultValue: "18", suffix: "%", step: "0.1" },
  ], [
    { id: "savedAmount", label: "Saved Amount", format: "currency" },
    { id: "buyNowTotalCost", label: "Buy Now Total Cost", format: "currency" },
    { id: "waitTotalCost", label: "Wait Total Cost", format: "currency" },
    { id: "savingsByWaiting", label: "Savings by Waiting", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "credit-card-balance-transfer": def("credit-card-balance-transfer", [
    { id: "balance", label: "Balance", defaultValue: "5000", suffix: "$" },
    { id: "currentRate", label: "Current Rate", defaultValue: "22", suffix: "%", step: "0.1" },
    { id: "newRate", label: "New Rate", defaultValue: "0", suffix: "%", step: "0.1" },
    { id: "transferFeePercent", label: "Transfer Fee", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "monthsToPayoff", label: "Months to Payoff", defaultValue: "18", suffix: "months" },
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "0", suffix: "$" },
  ], [
    { id: "currentTotalInterest", label: "Current Total Interest", format: "currency" },
    { id: "newTotalInterest", label: "New Total Interest", format: "currency" },
    { id: "transferFee", label: "Transfer Fee", format: "currency" },
    { id: "netSavings", label: "Net Savings", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "credit-card-cash-advance": def("credit-card-cash-advance", [
    { id: "advanceAmount", label: "Advance Amount", defaultValue: "1000", suffix: "$" },
    { id: "feePercent", label: "Fee Percent", defaultValue: "5", suffix: "%", step: "0.1" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "25", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "6", suffix: "months" },
  ], [
    { id: "cashAdvanceFee", label: "Cash Advance Fee", format: "currency" },
    { id: "totalInterest", label: "Total Interest", format: "currency" },
    { id: "totalCost", label: "Total Cost", format: "currency" },
    { id: "monthsToPayoff", label: "Months to Payoff", format: "months", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "credit-card-minimum-payment": def("credit-card-minimum-payment", [
    { id: "balance", label: "Balance", defaultValue: "5000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "22", suffix: "%", step: "0.1" },
    { id: "minimumPercent", label: "Minimum Payment (%)", defaultValue: "2", suffix: "%", step: "0.1" },
    { id: "minimumDollar", label: "Minimum Payment ($)", defaultValue: "25", suffix: "$" },
  ], [
    { id: "monthsToPayoff", label: "Months to Payoff", format: "months", highlight: true },
    { id: "totalInterest", label: "Total Interest", format: "currency" },
    { id: "totalPaid", label: "Total Paid", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "credit-card-payoff": def("credit-card-payoff", [
    { id: "balance", label: "Balance", defaultValue: "5000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "22", suffix: "%", step: "0.1" },
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "200", suffix: "$" },
  ], [
    { id: "monthsToPayoff", label: "Months to Payoff", format: "months", highlight: true },
    { id: "totalInterest", label: "Total Interest", format: "currency" },
    { id: "totalPaid", label: "Total Paid", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "credit-card-rewards": def("credit-card-rewards", [
    { id: "annualSpending", label: "Annual Spending", defaultValue: "24000", suffix: "$" },
    { id: "rewardRate", label: "Reward Rate", defaultValue: "2", suffix: "%", step: "0.1" },
    { id: "annualFee", label: "Annual Fee", defaultValue: "95", suffix: "$" },
  ], [
    { id: "grossRewards", label: "Gross Rewards", format: "currency" },
    { id: "netRewards", label: "Net Rewards", format: "currency", highlight: true },
    { id: "effectiveRewardRate", label: "Effective Reward Rate", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "extra-debt-payments": def("extra-debt-payments", [
    { id: "balance", label: "Balance", defaultValue: "10000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "15", suffix: "%", step: "0.1" },
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "250", suffix: "$" },
    { id: "extraPayment", label: "Extra Payment", defaultValue: "100", suffix: "$" },
  ], [
    { id: "monthsSaved", label: "Months Saved", format: "months", highlight: true },
    { id: "interestSaved", label: "Interest Saved", format: "currency", highlight: true },
    { id: "standardMonths", label: "Standard Payoff", format: "months" },
    { id: "acceleratedMonths", label: "Accelerated Payoff", format: "months" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "closing-costs-impact": def("closing-costs-impact", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "300000", suffix: "$" },
    { id: "rateWithPoints", label: "Rate With Points", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "rateWithoutPoints", label: "Rate Without Points", defaultValue: "6.5", suffix: "%", step: "0.1" },
    { id: "pointsCost", label: "Points Cost", defaultValue: "3000", suffix: "$" },
    { id: "months", label: "Loan Term", defaultValue: "360", suffix: "months" },
  ], [
    { id: "paymentWithPoints", label: "Payment With Points", format: "currency" },
    { id: "paymentWithoutPoints", label: "Payment Without Points", format: "currency" },
    { id: "monthlySavings", label: "Monthly Savings", format: "currency", highlight: true },
    { id: "breakEvenMonths", label: "Break-Even Months", format: "months", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "home-affordability": def("home-affordability", [
    { id: "annualIncome", label: "Annual Income", defaultValue: "100000", suffix: "$" },
    { id: "monthlyDebts", label: "Monthly Debts", defaultValue: "500", suffix: "$" },
    { id: "downPayment", label: "Down Payment", defaultValue: "50000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6.5", suffix: "%", step: "0.1" },
    { id: "loanTermMonths", label: "Loan Term (Months)", defaultValue: "360", suffix: "months" },
    { id: "maxHousingRatio", label: "Max Housing Ratio", defaultValue: "28", suffix: "%", step: "0.1" },
    { id: "annualPropertyTax", label: "Annual Property Tax", defaultValue: "4000", suffix: "$" },
    { id: "annualInsurance", label: "Annual Insurance", defaultValue: "1500", suffix: "$" },
  ], [
    { id: "maxMonthlyHousing", label: "Max Monthly Housing", format: "currency", highlight: true },
    { id: "maxLoanAmount", label: "Max Loan Amount", format: "currency", highlight: true },
    { id: "affordableHomePrice", label: "Affordable Home Price", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "interest-only-vs-traditional": def("interest-only-vs-traditional", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "300000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6.5", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "360", suffix: "months" },
  ], [
    { id: "interestOnlyPayment", label: "Interest-Only Payment", format: "currency" },
    { id: "traditionalPayment", label: "Traditional Payment", format: "currency" },
    { id: "paymentDifference", label: "Payment Difference", format: "currency" },
    { id: "interestOnlyTotalInterest", label: "Interest-Only Total Interest", format: "currency" },
    { id: "traditionalTotalInterest", label: "Traditional Total Interest", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "mortgage-refinance": def("mortgage-refinance", [
    { id: "currentBalance", label: "Current Balance", defaultValue: "280000", suffix: "$" },
    { id: "currentRate", label: "Current Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "monthsRemaining", label: "Months Remaining", defaultValue: "300", suffix: "months" },
    { id: "newRate", label: "New Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "newMonths", label: "New Loan Term (Months)", defaultValue: "360", suffix: "months" },
    { id: "closingCosts", label: "Closing Costs", defaultValue: "5000", suffix: "$" },
  ], [
    { id: "currentPayment", label: "Current Payment", format: "currency" },
    { id: "newPayment", label: "New Payment", format: "currency" },
    { id: "monthlySavings", label: "Monthly Savings", format: "currency", highlight: true },
    { id: "breakEvenMonths", label: "Break-Even Months", format: "months", highlight: true },
    { id: "lifetimeSavings", label: "Lifetime Savings", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "buy-or-rent": def("buy-or-rent", [
    { id: "homePrice", label: "Home Price", defaultValue: "400000", suffix: "$" },
    { id: "downPayment", label: "Down Payment", defaultValue: "80000", suffix: "$" },
    { id: "mortgageRate", label: "Mortgage Rate", defaultValue: "6.5", suffix: "%", step: "0.1" },
    { id: "mortgageYears", label: "Mortgage Years", defaultValue: "30", suffix: "years" },
    { id: "monthlyRent", label: "Monthly Rent", defaultValue: "2000", suffix: "$" },
    { id: "rentIncreasePercent", label: "Rent Increase", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "appreciationPercent", label: "Appreciation", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "7", suffix: "years" },
    { id: "annualMaintenance", label: "Annual Maintenance", defaultValue: "3000", suffix: "$" },
    { id: "annualPropertyTax", label: "Annual Property Tax", defaultValue: "5000", suffix: "$" },
  ], [
    { id: "buyNetCost", label: "Buy Net Cost", format: "currency", highlight: true },
    { id: "rentTotalCost", label: "Rent Total Cost", format: "currency" },
    { id: "costDifference", label: "Cost Difference", format: "currency", highlight: true },
    { id: "endingHomeEquity", label: "Ending Home Equity", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "mortgage-points": def("mortgage-points", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "300000", suffix: "$" },
    { id: "pointsPercent", label: "Points Percent", defaultValue: "1", suffix: "%", step: "0.1" },
    { id: "rateReduction", label: "Rate Reduction", defaultValue: "0.25", suffix: "%", step: "0.1" },
    { id: "baseRate", label: "Base Rate", defaultValue: "6.75", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "360", suffix: "months" },
  ], [
    { id: "pointsCost", label: "Points Cost", format: "currency" },
    { id: "rateWithPoints", label: "Rate With Points", format: "number" },
    { id: "monthlySavings", label: "Monthly Savings", format: "currency", highlight: true },
    { id: "breakEvenMonths", label: "Break-Even Months", format: "months", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "retirement-savings-sufficient": def("retirement-savings-sufficient", [
    { id: "currentSavings", label: "Current Savings", defaultValue: "150000", suffix: "$" },
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "500", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "yearsToRetirement", label: "Years to Retirement", defaultValue: "20", suffix: "years" },
    { id: "desiredAnnualIncome", label: "Desired Annual Income", defaultValue: "60000", suffix: "$" },
    { id: "withdrawalRate", label: "Withdrawal Rate", defaultValue: "4", suffix: "%", step: "0.1" },
  ], [
    { id: "projectedSavings", label: "Projected Savings", format: "currency", highlight: true },
    { id: "neededNestEgg", label: "Needed Nest Egg", format: "currency", highlight: true },
    { id: "shortfall", label: "Shortfall", format: "currency", highlight: true },
    { id: "surplus", label: "Surplus", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "inflation-retirement-income": def("inflation-retirement-income", [
    { id: "currentIncomeNeed", label: "Current Monthly Income Need", defaultValue: "5000", suffix: "$" },
    { id: "inflationRate", label: "Inflation Rate", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "yearsToRetirement", label: "Years to Retirement", defaultValue: "25", suffix: "years" },
  ], [
    { id: "futureMonthlyNeed", label: "Future Monthly Need", format: "currency" },
    { id: "futureAnnualNeed", label: "Future Annual Need", format: "currency" },
    { id: "purchasingPowerLoss", label: "Purchasing Power Loss", format: "currency" },
    { id: "increaseAmount", label: "Increase Amount", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "when-start-saving-retirement": def("when-start-saving-retirement", [
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "400", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "yearsToRetirement", label: "Years to Retirement", defaultValue: "30", suffix: "years" },
    { id: "targetAmount", label: "Target Amount", defaultValue: "1000000", suffix: "$" },
    { id: "delayYears", label: "Delay (Years)", defaultValue: "5", suffix: "years" },
  ], [
    { id: "valueIfStartNow", label: "Value If Start Now", format: "currency" },
    { id: "valueIfStartLater", label: "Value If Start Later", format: "currency" },
    { id: "costOfDelay", label: "Cost of Delay", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "burial-final-expenses": def("burial-final-expenses", [
    { id: "funeralCost", label: "Funeral Cost", defaultValue: "10000", suffix: "$" },
    { id: "medicalBills", label: "Medical Bills", defaultValue: "5000", suffix: "$" },
    { id: "legalFees", label: "Legal Fees", defaultValue: "3000", suffix: "$" },
    { id: "monthsToSave", label: "Months to Save", defaultValue: "60", suffix: "months" },
  ], [
    { id: "totalFinalExpenses", label: "Total Final Expenses", format: "currency" },
    { id: "monthlySavingsNeeded", label: "Monthly Savings Needed", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "disability-insurance-needed": def("disability-insurance-needed", [
    { id: "annualIncome", label: "Annual Income", defaultValue: "80000", suffix: "$" },
    { id: "currentCoverage", label: "Current Coverage", defaultValue: "0", suffix: "$" },
    { id: "monthlyExpenses", label: "Monthly Expenses", defaultValue: "4000", suffix: "$" },
    { id: "benefitPercent", label: "Benefit Percent", defaultValue: "60", suffix: "%", step: "0.1" },
  ], [
    { id: "recommendedMonthlyBenefit", label: "Recommended Monthly Benefit", format: "currency", highlight: true },
    { id: "coverageGap", label: "Coverage Gap", format: "currency", highlight: true },
    { id: "currentCoverage", label: "Current Coverage", format: "number" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "future-value-annuity": def("future-value-annuity", [
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "500", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "5", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "20", suffix: "years" },
  ], [
    { id: "futureValue", label: "Future Value", format: "currency", highlight: true },
    { id: "totalContributions", label: "Total Contributions", format: "currency" },
    { id: "investmentGrowth", label: "Investment Growth", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "hsa-vs-comprehensive": def("hsa-vs-comprehensive", [
    { id: "hdhpPremium", label: "HDHP Premium (Monthly)", defaultValue: "400", suffix: "$" },
    { id: "hdhpDeductible", label: "HDHP Deductible", defaultValue: "3000", suffix: "$" },
    { id: "employerHsaContribution", label: "Employer HSA Contribution", defaultValue: "1000", suffix: "$" },
    { id: "comprehensivePremium", label: "Comprehensive Premium (Monthly)", defaultValue: "550", suffix: "$" },
    { id: "comprehensiveDeductible", label: "Comprehensive Deductible", defaultValue: "500", suffix: "$" },
    { id: "expectedMedical", label: "Expected Medical Expenses", defaultValue: "2000", suffix: "$" },
  ], [
    { id: "hdhpAnnualCost", label: "HDHP Annual Cost", format: "currency" },
    { id: "comprehensiveAnnualCost", label: "Comprehensive Annual Cost", format: "currency" },
    { id: "savings", label: "Savings", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "life-insurance-proceeds-duration": def("life-insurance-proceeds-duration", [
    { id: "deathBenefit", label: "Death Benefit", defaultValue: "500000", suffix: "$" },
    { id: "monthlyExpenses", label: "Monthly Expenses", defaultValue: "4000", suffix: "$" },
    { id: "investmentReturn", label: "Investment Return", defaultValue: "4", suffix: "%", step: "0.1" },
  ], [
    { id: "monthsProceedsLast", label: "Months Proceeds Last", format: "months" },
    { id: "yearsProceedsLast", label: "Years Proceeds Last", format: "years", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "life-insurance-needed": def("life-insurance-needed", [
    { id: "annualIncome", label: "Annual Income", defaultValue: "75000", suffix: "$" },
    { id: "yearsToReplace", label: "Years to Replace", defaultValue: "10", suffix: "years" },
    { id: "existingCoverage", label: "Existing Coverage", defaultValue: "100000", suffix: "$" },
    { id: "outstandingDebts", label: "Outstanding Debts", defaultValue: "150000", suffix: "$" },
    { id: "finalExpenses", label: "Final Expenses", defaultValue: "15000", suffix: "$" },
  ], [
    { id: "totalCoverageNeeded", label: "Total Coverage Needed", format: "currency" },
    { id: "additionalCoverageNeeded", label: "Additional Coverage Needed", format: "currency", highlight: true },
    { id: "existingCoverage", label: "Existing Coverage", format: "number" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "retired-savings-duration": def("retired-savings-duration", [
    { id: "retirementSavings", label: "Retirement Savings", defaultValue: "500000", suffix: "$" },
    { id: "monthlyWithdrawal", label: "Monthly Withdrawal", defaultValue: "3000", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "5", suffix: "%", step: "0.1" },
  ], [
    { id: "monthsSavingsLast", label: "Months Savings Last", format: "months", highlight: true },
    { id: "yearsSavingsLast", label: "Years Savings Last", format: "years", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "lifetime-earnings": def("lifetime-earnings", [
    { id: "currentSalary", label: "Current Salary", defaultValue: "60000", suffix: "$" },
    { id: "annualRaisePercent", label: "Annual Raise", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "yearsWorking", label: "Years Working", defaultValue: "35", suffix: "years" },
  ], [
    { id: "lifetimeEarnings", label: "Lifetime Earnings", format: "currency", highlight: true },
    { id: "finalYearSalary", label: "Final Year Salary", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "long-term-care-insurance": def("long-term-care-insurance", [
    { id: "dailyCost", label: "Daily Cost", defaultValue: "250", suffix: "$" },
    { id: "yearsOfCare", label: "Years of Care", defaultValue: "3", suffix: "years" },
    { id: "inflationRate", label: "Inflation Rate", defaultValue: "4", suffix: "%", step: "0.1" },
    { id: "yearsUntilNeed", label: "Years Until Need", defaultValue: "20", suffix: "years" },
    { id: "existingCoverage", label: "Existing Coverage", defaultValue: "100000", suffix: "$" },
  ], [
    { id: "projectedTotalCost", label: "Projected Total Cost", format: "currency", highlight: true },
    { id: "coverageGap", label: "Coverage Gap", format: "currency", highlight: true },
    { id: "futureDailyCost", label: "Future Daily Cost", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "allowance-investment-return": def("allowance-investment-return", [
    { id: "weeklyAllowance", label: "Weekly Allowance", defaultValue: "10", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "10", suffix: "years" },
  ], [
    { id: "futureValue", label: "Future Value", format: "currency", highlight: true },
    { id: "totalContributions", label: "Total Contributions", format: "currency" },
    { id: "investmentGrowth", label: "Investment Growth", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "chore-value-kids": def("chore-value-kids", [
    { id: "hoursPerWeek", label: "Hours Per Week", defaultValue: "5" },
    { id: "hourlyRate", label: "Hourly Rate", defaultValue: "5", suffix: "$" },
    { id: "weeksPerYear", label: "Weeks Per Year", defaultValue: "52" },
  ], [
    { id: "weeklyEarnings", label: "Weekly Earnings", format: "currency", highlight: true },
    { id: "annualEarnings", label: "Annual Earnings", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "compound-interest-kids": def("compound-interest-kids", [
    { id: "initialDeposit", label: "Initial Deposit", defaultValue: "100", suffix: "$" },
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "25", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "18", suffix: "years" },
  ], [
    { id: "futureValue", label: "Future Value", format: "currency", highlight: true },
    { id: "totalContributions", label: "Total Contributions", format: "currency" },
    { id: "compoundGrowth", label: "Compound Growth", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "lemonade-stand": def("lemonade-stand", [
    { id: "cupsSold", label: "Cups Sold", defaultValue: "50" },
    { id: "pricePerCup", label: "Price Per Cup", defaultValue: "1", suffix: "$" },
    { id: "costPerCup", label: "Cost Per Cup", defaultValue: "0.25", suffix: "$" },
    { id: "fixedCosts", label: "Fixed Costs", defaultValue: "10", suffix: "$" },
  ], [
    { id: "revenue", label: "Revenue", format: "currency" },
    { id: "totalCosts", label: "Total Costs", format: "currency" },
    { id: "profit", label: "Profit", format: "currency", highlight: true },
    { id: "profitPerCup", label: "Profit Per Cup", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "penny-doubles": def("penny-doubles", [
    { id: "days", label: "Days", defaultValue: "30" },
    { id: "alternativeAmount", label: "Alternative Amount", defaultValue: "1000000", suffix: "$" },
  ], [
    { id: "pennyDoublesValue", label: "Penny Doubles Value", format: "currency", highlight: true },
    { id: "alternativeAmount", label: "Alternative Amount", format: "currency" },
    { id: "difference", label: "Difference", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "asset-allocation": def("asset-allocation", [
    { id: "totalPortfolio", label: "Total Portfolio", defaultValue: "100000", suffix: "$" },
    { id: "stocksPercent", label: "Stocks (%)", defaultValue: "60", suffix: "%", step: "0.1" },
    { id: "bondsPercent", label: "Bonds (%)", defaultValue: "30", suffix: "%", step: "0.1" },
    { id: "cashPercent", label: "Cash (%)", defaultValue: "10", suffix: "%", step: "0.1" },
  ], [
    { id: "stocksValue", label: "Stocks Value", format: "currency" },
    { id: "bondsValue", label: "Bonds Value", format: "currency" },
    { id: "cashValue", label: "Cash Value", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "dividend-reinvestment": def("dividend-reinvestment", [
    { id: "initialInvestment", label: "Initial Investment", defaultValue: "10000", suffix: "$" },
    { id: "dividendYield", label: "Dividend Yield", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "20", suffix: "years" },
  ], [
    { id: "valueWithReinvestment", label: "Value With Reinvestment", format: "currency", highlight: true },
    { id: "valueWithoutReinvestment", label: "Value Without Reinvestment", format: "currency" },
    { id: "reinvestmentBenefit", label: "Reinvestment Benefit", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "employee-stock-options": def("employee-stock-options", [
    { id: "numOptions", label: "Number of Options", defaultValue: "1000" },
    { id: "strikePrice", label: "Strike Price", defaultValue: "10", suffix: "$" },
    { id: "currentPrice", label: "Current Price", defaultValue: "25", suffix: "$" },
  ], [
    { id: "intrinsicValue", label: "Intrinsic Value", format: "currency", highlight: true },
    { id: "valuePerOption", label: "Value Per Option", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "invest-or-pay-debt": def("invest-or-pay-debt", [
    { id: "debtBalance", label: "Debt Balance", defaultValue: "10000", suffix: "$" },
    { id: "debtRate", label: "Debt Rate", defaultValue: "18", suffix: "%", step: "0.1" },
    { id: "investmentReturn", label: "Investment Return", defaultValue: "8", suffix: "%", step: "0.1" },
    { id: "extraPayment", label: "Extra Payment", defaultValue: "200", suffix: "$" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
  ], [
    { id: "debtInterestSaved", label: "Debt Interest Saved", format: "currency", highlight: true },
    { id: "investmentFutureValue", label: "Investment Future Value", format: "currency" },
    { id: "netBenefitPayDebt", label: "Net Benefit (Pay Debt)", format: "currency", highlight: true },
    { id: "netBenefitInvest", label: "Net Benefit (Invest)", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "lump-sum-vs-dca": def("lump-sum-vs-dca", [
    { id: "lumpSum", label: "Lump Sum", defaultValue: "50000", suffix: "$" },
    { id: "monthlyDCA", label: "Monthly DCA", defaultValue: "5000", suffix: "$" },
    { id: "months", label: "Loan Term", defaultValue: "10", suffix: "months" },
    { id: "returnRate", label: "Return Rate", defaultValue: "8", suffix: "%", step: "0.1" },
  ], [
    { id: "lumpSumFutureValue", label: "Lump Sum Future Value", format: "currency", highlight: true },
    { id: "dcaFutureValue", label: "DCA Future Value", format: "currency", highlight: true },
    { id: "difference", label: "Difference", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "percentage-change": def("percentage-change", [
    { id: "oldValue", label: "Old Value", defaultValue: "100", suffix: "$" },
    { id: "newValue", label: "New Value", defaultValue: "125", suffix: "$" },
  ], [
    { id: "percentChange", label: "Percent Change", format: "percent", highlight: true },
    { id: "absoluteChange", label: "Absolute Change", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "portfolio-rebalancing": def("portfolio-rebalancing", [
    { id: "totalValue", label: "Total Value", defaultValue: "200000", suffix: "$" },
    { id: "currentStocksPercent", label: "Current Stocks (%)", defaultValue: "70", suffix: "%", step: "0.1" },
    { id: "targetStocksPercent", label: "Target Stocks (%)", defaultValue: "60", suffix: "%", step: "0.1" },
    { id: "currentBondsPercent", label: "Current Bonds (%)", defaultValue: "20", suffix: "%", step: "0.1" },
    { id: "targetBondsPercent", label: "Target Bonds (%)", defaultValue: "30", suffix: "%", step: "0.1" },
  ], [
    { id: "stocksAdjustment", label: "Stocks Adjustment", format: "currency" },
    { id: "bondsAdjustment", label: "Bonds Adjustment", format: "currency" },
    { id: "sellStocksAmount", label: "Sell Stocks Amount", format: "currency" },
    { id: "buyBondsAmount", label: "Buy Bonds Amount", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "roth-vs-traditional-ira": def("roth-vs-traditional-ira", [
    { id: "annualContribution", label: "Annual Contribution", defaultValue: "7000", suffix: "$" },
    { id: "years", label: "Years", defaultValue: "25", suffix: "years" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "marginalTaxNow", label: "Marginal Tax Rate (Now)", defaultValue: "22", suffix: "%", step: "0.1" },
    { id: "marginalTaxRetirement", label: "Marginal Tax Rate (Retirement)", defaultValue: "15", suffix: "%", step: "0.1" },
  ], [
    { id: "traditionalAfterTax", label: "Traditional (After Tax)", format: "currency", highlight: true },
    { id: "rothAfterTax", label: "Roth (After Tax)", format: "currency", highlight: true },
    { id: "advantage", label: "Advantage", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "exercise-stock-options": def("exercise-stock-options", [
    { id: "numOptions", label: "Number of Options", defaultValue: "500" },
    { id: "strikePrice", label: "Strike Price", defaultValue: "15", suffix: "$" },
    { id: "currentPrice", label: "Current Price", defaultValue: "30", suffix: "$" },
    { id: "expectedGrowth", label: "Expected Growth", defaultValue: "8", suffix: "%", step: "0.1" },
    { id: "yearsToHold", label: "Years to Hold", defaultValue: "3", suffix: "years" },
  ], [
    { id: "valueIfExerciseNow", label: "Value If Exercise Now", format: "currency", highlight: true },
    { id: "projectedValueIfHold", label: "Projected Value If Hold", format: "currency", highlight: true },
    { id: "exerciseCost", label: "Exercise Cost", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "apr-vs-interest-rate": def("apr-vs-interest-rate", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "20000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "fees", label: "Fees", defaultValue: "500", suffix: "$" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
  ], [
    { id: "monthlyPayment", label: "Monthly Payment", format: "currency", highlight: true },
    { id: "statedRate", label: "Stated Rate", format: "percent" },
    { id: "effectiveApr", label: "Effective APR", format: "currency", highlight: true },
    { id: "totalCost", label: "Total Cost", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "balloon-payment": def("balloon-payment", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "30000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
    { id: "balloonPercent", label: "Balloon Percent", defaultValue: "30", suffix: "%", step: "0.1" },
  ], [
    { id: "monthlyPayment", label: "Monthly Payment", format: "currency", highlight: true },
    { id: "balloonPayment", label: "Balloon Payment", format: "currency", highlight: true },
    { id: "totalPaid", label: "Total Paid", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "loan-simulator": def("loan-simulator", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "25000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "60", suffix: "months" },
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "0", suffix: "$" },
    { id: "extraPayment", label: "Extra Payment", defaultValue: "0", suffix: "$" },
  ], [
    { id: "monthlyPayment", label: "Monthly Payment", format: "currency", highlight: true },
    { id: "monthsToPayoff", label: "Months to Payoff", format: "months", highlight: true },
    { id: "totalInterest", label: "Total Interest", format: "currency" },
    { id: "totalPaid", label: "Total Paid", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "debt-consolidation": def("debt-consolidation", [
    { id: "debt1Balance", label: "Debt 1 Balance", defaultValue: "8000", suffix: "$" },
    { id: "debt1Rate", label: "Debt 1 Rate", defaultValue: "22", suffix: "%", step: "0.1" },
    { id: "debt2Balance", label: "Debt 2 Balance", defaultValue: "5000", suffix: "$" },
    { id: "debt2Rate", label: "Debt 2 Rate", defaultValue: "18", suffix: "%", step: "0.1" },
    { id: "consolidatedRate", label: "Consolidated Rate", defaultValue: "12", suffix: "%", step: "0.1" },
    { id: "consolidatedMonths", label: "Consolidated Term (Months)", defaultValue: "48", suffix: "months" },
  ], [
    { id: "currentTotalPayment", label: "Current Total Payment", format: "currency" },
    { id: "consolidatedPayment", label: "Consolidated Payment", format: "currency", highlight: true },
    { id: "currentTotalInterest", label: "Current Total Interest", format: "currency" },
    { id: "consolidatedTotalInterest", label: "Consolidated Total Interest", format: "currency" },
    { id: "interestSavings", label: "Interest Savings", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "student-loan-repayment": def("student-loan-repayment", [
    { id: "loanAmount", label: "Loan Amount", defaultValue: "35000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "5.5", suffix: "%", step: "0.1" },
    { id: "repaymentYears", label: "Repayment Years", defaultValue: "10", suffix: "years" },
  ], [
    { id: "monthlyPayment", label: "Monthly Payment", format: "currency", highlight: true },
    { id: "totalInterest", label: "Total Interest", format: "currency" },
    { id: "totalPaid", label: "Total Paid", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "401k-contribution-impact": def("401k-contribution-impact", [
    { id: "grossPay", label: "Gross Pay", defaultValue: "5000", suffix: "$" },
    { id: "contributionPercent", label: "Contribution Percent", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "marginalTaxRate", label: "Marginal Tax Rate", defaultValue: "22", suffix: "%", step: "0.1" },
  ], [
    { id: "contributionAmount", label: "Contribution Amount", format: "currency" },
    { id: "taxSavings", label: "Tax Savings", format: "currency", highlight: true },
    { id: "netPayReduction", label: "Net Pay Reduction", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "hourly-to-salary": def("hourly-to-salary", [
    { id: "hourlyWage", label: "Hourly Wage", defaultValue: "25", suffix: "$" },
    { id: "hoursPerWeek", label: "Hours Per Week", defaultValue: "40" },
    { id: "weeksPerYear", label: "Weeks Per Year", defaultValue: "52" },
  ], [
    { id: "annualSalary", label: "Annual Salary", format: "currency", highlight: true },
    { id: "monthlySalary", label: "Monthly Salary", format: "currency" },
    { id: "weeklyPay", label: "Weekly Pay", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "overtime-pay": def("overtime-pay", [
    { id: "hourlyRate", label: "Hourly Rate", defaultValue: "20", suffix: "$" },
    { id: "overtimeHours", label: "Overtime Hours", defaultValue: "10" },
    { id: "overtimeMultiplier", label: "Overtime Multiplier", defaultValue: "1.5" },
    { id: "regularHours", label: "Regular Hours", defaultValue: "40" },
  ], [
    { id: "regularPay", label: "Regular Pay", format: "currency" },
    { id: "overtimePay", label: "Overtime Pay", format: "currency" },
    { id: "totalPay", label: "Total Pay", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "paycheck-comparison": def("paycheck-comparison", [
    { id: "salary1", label: "Salary (Job 1)", defaultValue: "75000", suffix: "$" },
    { id: "salary2", label: "Salary (Job 2)", defaultValue: "82000", suffix: "$" },
    { id: "taxRate1", label: "Tax Rate (Job 1)", defaultValue: "22", suffix: "%", step: "0.1" },
    { id: "taxRate2", label: "Tax Rate (Job 2)", defaultValue: "24", suffix: "%", step: "0.1" },
  ], [
    { id: "netPay1", label: "Net Pay (Job 1)", format: "currency", highlight: true },
    { id: "netPay2", label: "Net Pay (Job 2)", format: "currency", highlight: true },
    { id: "difference", label: "Difference", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "pay-frequency-impact": def("pay-frequency-impact", [
    { id: "annualSalary", label: "Annual Salary", defaultValue: "60000", suffix: "$" },
    { id: "taxRate", label: "Tax Rate", defaultValue: "22", suffix: "%", step: "0.1" },
  ], [
    { id: "weeklyNet", label: "Weekly Net", format: "currency" },
    { id: "biweeklyNet", label: "Biweekly Net", format: "currency" },
    { id: "semimonthlyNet", label: "Semi-Monthly Net", format: "currency" },
    { id: "monthlyNet", label: "Monthly Net", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "fix-and-flip": def("fix-and-flip", [
    { id: "purchasePrice", label: "Purchase Price", defaultValue: "200000", suffix: "$" },
    { id: "rehabCost", label: "Rehab Cost", defaultValue: "40000", suffix: "$" },
    { id: "holdingCosts", label: "Holding Costs", defaultValue: "8000", suffix: "$" },
    { id: "salePrice", label: "Sale Price", defaultValue: "320000", suffix: "$" },
    { id: "sellingCosts", label: "Selling Costs", defaultValue: "19200", suffix: "$" },
  ], [
    { id: "totalInvestment", label: "Total Investment", format: "currency" },
    { id: "netProfit", label: "Net Profit", format: "currency", highlight: true },
    { id: "roi", label: "ROI", format: "percent", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "gross-rent-multiplier": def("gross-rent-multiplier", [
    { id: "propertyPrice", label: "Property Price", defaultValue: "300000", suffix: "$" },
    { id: "monthlyRent", label: "Monthly Rent", defaultValue: "2000", suffix: "$" },
  ], [
    { id: "grossRentMultiplier", label: "Gross Rent Multiplier", format: "percent", highlight: true },
    { id: "annualGrossRent", label: "Annual Gross Rent", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "land-value": def("land-value", [
    { id: "totalPropertyValue", label: "Total Property Value", defaultValue: "400000", suffix: "$" },
    { id: "landPercent", label: "Land (%)", defaultValue: "25" },
  ], [
    { id: "landValue", label: "Land Value", format: "currency" },
    { id: "improvementValue", label: "Improvement Value", format: "currency" },
    { id: "landPercent", label: "Land Percent", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "real-estate-cap-rate": def("real-estate-cap-rate", [
    { id: "netOperatingIncome", label: "Net Operating Income", defaultValue: "24000", suffix: "$" },
    { id: "propertyValue", label: "Property Value", defaultValue: "350000", suffix: "$" },
  ], [
    { id: "capRate", label: "Cap Rate", format: "percent", highlight: true },
    { id: "netOperatingIncome", label: "Net Operating Income", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "real-estate-commission": def("real-estate-commission", [
    { id: "salePrice", label: "Sale Price", defaultValue: "450000", suffix: "$" },
    { id: "commissionPercent", label: "Commission Percent", defaultValue: "6", suffix: "%", step: "0.1" },
  ], [
    { id: "totalCommission", label: "Total Commission", format: "currency", highlight: true },
    { id: "sellerAgentShare", label: "Seller Agent Share", format: "currency" },
    { id: "netProceeds", label: "Net Proceeds", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "rental-property": def("rental-property", [
    { id: "purchasePrice", label: "Purchase Price", defaultValue: "300000", suffix: "$" },
    { id: "downPayment", label: "Down Payment", defaultValue: "60000", suffix: "$" },
    { id: "loanRate", label: "Loan Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "loanYears", label: "Loan Years", defaultValue: "30", suffix: "years" },
    { id: "monthlyRent", label: "Monthly Rent", defaultValue: "2200", suffix: "$" },
    { id: "monthlyExpenses", label: "Monthly Expenses", defaultValue: "400", suffix: "$" },
    { id: "vacancyRate", label: "Vacancy Rate", defaultValue: "5", suffix: "%", step: "0.1" },
    { id: "closingCosts", label: "Closing Costs", defaultValue: "6000", suffix: "$" },
  ], [
    { id: "monthlyCashFlow", label: "Monthly Cash Flow", format: "currency", highlight: true },
    { id: "annualCashFlow", label: "Annual Cash Flow", format: "currency" },
    { id: "cashOnCashReturn", label: "Cash-on-Cash Return", format: "percent", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "becoming-millionaire": def("becoming-millionaire", [
    { id: "currentSavings", label: "Current Savings", defaultValue: "50000", suffix: "$" },
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "1000", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "8", suffix: "%", step: "0.1" },
    { id: "goalAmount", label: "Goal Amount", defaultValue: "1000000", suffix: "$" },
  ], [
    { id: "yearsToGoal", label: "Years to Goal", format: "years", highlight: true },
    { id: "goalAmount", label: "Goal Amount", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "cd-calculator": def("cd-calculator", [
    { id: "deposit", label: "Deposit", defaultValue: "10000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "4.5", suffix: "%", step: "0.1" },
    { id: "months", label: "Loan Term", defaultValue: "12", suffix: "months" },
  ], [
    { id: "maturityValue", label: "Maturity Value", format: "currency", highlight: true },
    { id: "interestEarned", label: "Interest Earned", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "college-savings": def("college-savings", [
    { id: "currentSavings", label: "Current Savings", defaultValue: "5000", suffix: "$" },
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "200", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "15", suffix: "years" },
    { id: "targetAmount", label: "Target Amount", defaultValue: "100000", suffix: "$" },
  ], [
    { id: "projectedSavings", label: "Projected Savings", format: "currency", highlight: true },
    { id: "targetAmount", label: "Target Amount", format: "currency" },
    { id: "shortfall", label: "Shortfall", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "compare-savings-rates": def("compare-savings-rates", [
    { id: "initialDeposit", label: "Initial Deposit", defaultValue: "25000", suffix: "$" },
    { id: "rate1", label: "Rate 1", defaultValue: "3" },
    { id: "rate2", label: "Rate 2", defaultValue: "4.5" },
    { id: "years", label: "Years", defaultValue: "5", suffix: "years" },
  ], [
    { id: "balanceAtRate1", label: "Balance at Rate 1", format: "currency" },
    { id: "balanceAtRate2", label: "Balance at Rate 2", format: "currency" },
    { id: "difference", label: "Difference", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "household-budget": def("household-budget", [
    { id: "monthlyIncome", label: "Monthly Income", defaultValue: "6000", suffix: "$" },
    { id: "housing", label: "Housing", defaultValue: "1800", suffix: "$" },
    { id: "transportation", label: "Transportation", defaultValue: "600", suffix: "$" },
    { id: "food", label: "Food", defaultValue: "500", suffix: "$" },
    { id: "utilities", label: "Utilities", defaultValue: "250", suffix: "$" },
    { id: "otherExpenses", label: "Other Expenses", defaultValue: "400", suffix: "$" },
  ], [
    { id: "totalExpenses", label: "Total Expenses", format: "currency" },
    { id: "monthlySurplus", label: "Monthly Surplus", format: "currency", highlight: true },
    { id: "savingsRate", label: "Savings Rate", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "impact-delaying-savings": def("impact-delaying-savings", [
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "500", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "7", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "30", suffix: "years" },
    { id: "delayYears", label: "Delay (Years)", defaultValue: "5", suffix: "years" },
  ], [
    { id: "valueIfStartNow", label: "Value If Start Now", format: "currency" },
    { id: "valueIfDelayed", label: "Value If Delayed", format: "currency" },
    { id: "costOfDelay", label: "Cost of Delay", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "fixed-deposit-returns": def("fixed-deposit-returns", [
    { id: "principal", label: "Principal", defaultValue: "50000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "5", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "3", suffix: "years" },
  ], [
    { id: "maturityAmount", label: "Maturity Amount", format: "currency" },
    { id: "interestEarned", label: "Interest Earned", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "rule-of-72": def("rule-of-72", [
    { id: "interestRate", label: "Interest Rate", defaultValue: "7", suffix: "%", step: "0.1" },
  ], [
    { id: "yearsToDouble", label: "Years to Double", format: "number", highlight: true },
    { id: "interestRate", label: "Interest Rate", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "simple-savings": def("simple-savings", [
    { id: "initialDeposit", label: "Initial Deposit", defaultValue: "1000", suffix: "$" },
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "200", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "4", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "10", suffix: "years" },
  ], [
    { id: "futureValue", label: "Future Value", format: "currency", highlight: true },
    { id: "totalContributions", label: "Total Contributions", format: "currency" },
    { id: "interestEarned", label: "Interest Earned", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "inflation-calculator": def("inflation-calculator", [
    { id: "currentAmount", label: "Current Amount", defaultValue: "100000", suffix: "$" },
    { id: "inflationRate", label: "Inflation Rate", defaultValue: "3", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "10", suffix: "years" },
  ], [
    { id: "futurePurchasingPower", label: "Future Purchasing Power", format: "currency", highlight: true },
    { id: "purchasingPowerLost", label: "Purchasing Power Lost", format: "currency" },
    { id: "equivalentToday", label: "Equivalent Today", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "savings-growth": def("savings-growth", [
    { id: "currentSavings", label: "Current Savings", defaultValue: "25000", suffix: "$" },
    { id: "monthlyContribution", label: "Monthly Contribution", defaultValue: "300", suffix: "$" },
    { id: "returnRate", label: "Return Rate", defaultValue: "6", suffix: "%", step: "0.1" },
    { id: "years", label: "Years", defaultValue: "15", suffix: "years" },
  ], [
    { id: "futureValue", label: "Future Value", format: "currency", highlight: true },
    { id: "totalContributions", label: "Total Contributions", format: "currency" },
    { id: "investmentGrowth", label: "Investment Growth", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "social-security-taxable": def("social-security-taxable", [
    { id: "ssBenefits", label: "Social Security Benefits", defaultValue: "24000", suffix: "$" },
    { id: "otherIncome", label: "Other Income", defaultValue: "30000", suffix: "$" },
    { id: "taxExemptInterest", label: "Tax-Exempt Interest", defaultValue: "0", suffix: "$" },
    { id: "filingStatus", label: "Filing Status", defaultValue: "0", type: "select", options: [{ value: "0", label: "Single" }, { value: "1", label: "Married Filing Jointly" }] },
  ], [
    { id: "provisionalIncome", label: "Provisional Income", format: "currency" },
    { id: "taxableBenefits", label: "Taxable Benefits", format: "currency", highlight: true },
    { id: "taxablePercent", label: "Taxable Percent", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "earned-income-credit": def("earned-income-credit", [
    { id: "earnedIncome", label: "Earned Income", defaultValue: "25000", suffix: "$" },
    { id: "qualifyingChildren", label: "Qualifying Children", defaultValue: "1" },
  ], [
    { id: "estimatedEic", label: "Estimated EIC", format: "currency", highlight: true },
    { id: "earnedIncome", label: "Earned Income", format: "currency" },
    { id: "qualifyingChildren", label: "Qualifying Children", format: "number" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "tax-savings-interest": def("tax-savings-interest", [
    { id: "interestPaid", label: "Interest Paid", defaultValue: "12000", suffix: "$" },
    { id: "marginalTaxRate", label: "Marginal Tax Rate", defaultValue: "24", suffix: "%", step: "0.1" },
  ], [
    { id: "taxSavings", label: "Tax Savings", format: "currency", highlight: true },
    { id: "afterTaxInterestCost", label: "After-Tax Interest Cost", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "taxable-equivalent-yield": def("taxable-equivalent-yield", [
    { id: "taxFreeYield", label: "Tax-Free Yield", defaultValue: "3" },
    { id: "marginalTaxRate", label: "Marginal Tax Rate", defaultValue: "24", suffix: "%", step: "0.1" },
  ], [
    { id: "taxableEquivalentYield", label: "Taxable Equivalent Yield", format: "percent", highlight: true },
    { id: "taxFreeYield", label: "Tax-Free Yield", format: "percent" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "career-path-affordability": def("career-path-affordability", [
    { id: "educationCost", label: "Education Cost", defaultValue: "80000", suffix: "$" },
    { id: "startingSalary", label: "Starting Salary", defaultValue: "55000", suffix: "$" },
    { id: "annualLivingExpenses", label: "Annual Living Expenses", defaultValue: "35000", suffix: "$" },
  ], [
    { id: "firstYearSurplus", label: "First Year Surplus", format: "currency" },
    { id: "yearsToBreakEven", label: "Years to Break Even", format: "years", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "college-budget": def("college-budget", [
    { id: "monthlyIncome", label: "Monthly Income", defaultValue: "800", suffix: "$" },
    { id: "tuitionShare", label: "Tuition Share", defaultValue: "0", suffix: "$" },
    { id: "housing", label: "Housing", defaultValue: "600", suffix: "$" },
    { id: "food", label: "Food", defaultValue: "250", suffix: "$" },
    { id: "books", label: "Books", defaultValue: "50", suffix: "$" },
    { id: "otherExpenses", label: "Other Expenses", defaultValue: "100", suffix: "$" },
  ], [
    { id: "totalExpenses", label: "Total Expenses", format: "currency" },
    { id: "monthlySurplus", label: "Monthly Surplus", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "campus-vs-home": def("campus-vs-home", [
    { id: "campusHousing", label: "Campus Housing (Annual)", defaultValue: "8000", suffix: "$" },
    { id: "mealPlan", label: "Meal Plan (Annual)", defaultValue: "5000", suffix: "$" },
    { id: "commutingCost", label: "Commuting Cost (Annual)", defaultValue: "2000", suffix: "$" },
    { id: "homeFoodCost", label: "Home Food Cost (Annual)", defaultValue: "3000", suffix: "$" },
    { id: "years", label: "Years", defaultValue: "4", suffix: "years" },
  ], [
    { id: "campusTotalCost", label: "Campus Total Cost", format: "currency", highlight: true },
    { id: "homeTotalCost", label: "Home Total Cost", format: "currency", highlight: true },
    { id: "savings", label: "Savings", format: "currency" },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "student-loan-extra-payment": def("student-loan-extra-payment", [
    { id: "loanBalance", label: "Loan Balance", defaultValue: "28000", suffix: "$" },
    { id: "interestRate", label: "Interest Rate", defaultValue: "5.5", suffix: "%", step: "0.1" },
    { id: "monthlyPayment", label: "Monthly Payment", defaultValue: "300", suffix: "$" },
    { id: "extraPayment", label: "Extra Payment", defaultValue: "100", suffix: "$" },
  ], [
    { id: "monthsSaved", label: "Months Saved", format: "months", highlight: true },
    { id: "interestSaved", label: "Interest Saved", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "summer-job-tax": def("summer-job-tax", [
    { id: "grossEarnings", label: "Gross Earnings", defaultValue: "4000", suffix: "$" },
    { id: "withholdingPercent", label: "Withholding Percent", defaultValue: "10", suffix: "%", step: "0.1" },
  ], [
    { id: "federalTax", label: "Federal Tax", format: "currency" },
    { id: "amountWithheld", label: "Amount Withheld", format: "currency" },
    { id: "estimatedRefund", label: "Estimated Refund", format: "currency", highlight: true },
    { id: "estimatedOwed", label: "Estimated Owed", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
  "college-education-value": def("college-education-value", [
    { id: "degreeAnnualEarnings", label: "Degree Annual Earnings", defaultValue: "65000", suffix: "$" },
    { id: "noDegreeAnnualEarnings", label: "No-Degree Annual Earnings", defaultValue: "38000", suffix: "$" },
    { id: "yearsWorking", label: "Years Working", defaultValue: "40", suffix: "years" },
    { id: "educationCost", label: "Education Cost", defaultValue: "100000", suffix: "$" },
  ], [
    { id: "lifetimeEarningsWithDegree", label: "Lifetime Earnings (With Degree)", format: "currency", highlight: true },
    { id: "lifetimeEarningsWithoutDegree", label: "Lifetime Earnings (Without Degree)", format: "currency", highlight: true },
    { id: "netEarningsPremium", label: "Net Earnings Premium", format: "currency", highlight: true },
    { id: "recommendation", label: "Recommendation", format: "text" },
  ]),
};

// Ensure all compute functions have definitions
void calculatorCatalog;
const _slugCheck: Record<string, CalculatorDefinition> = Object.fromEntries(
  Object.keys(computeFunctions).map((slug) => [slug, calculatorDefinitions[slug]]),
);
